version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install -r requirements-dev.txt

  pre_build:
  commands:
    - echo "Running CI checks inside CodePipeline..."
    - pwd
    - ls -la
    - ls -R
    - python --version
    - python -c "import os; print('CWD =', os.getcwd())"
    - python -c "import sys; print('SYS.PATH =', sys.path)"
    - python -c "import os; print('FILES =', os.listdir('.'))"
    - flake8 lambdas shared tests --max-line-length=100 --exclude=__pycache__
    - python -m pytest tests -v

  build:
    commands:
      - echo "Packaging Earthquake Lambda..."

      # Clean previous package
      - rm -rf package function.zip

      # Create temporary package directory
      - mkdir package

      # Copy Earthquake Lambda source
      - cp -r lambdas/earthquake/* package/

      # Copy shared modules
      - cp -r shared package/

      # Create deployment zip
      - cd package
      - zip -r ../function.zip .
      - cd ..

artifacts:
  files:
    - function.zip
  name: earthquake-etl-artifact